// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chapters.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapters (title, body, user_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, title, body, user_id, status, created_at
`

type CreateChapterParams struct {
	Title  pgtype.Text
	Body   pgtype.Text
	UserID int32
	Status pgtype.Text
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, createChapter,
		arg.Title,
		arg.Body,
		arg.UserID,
		arg.Status,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getChaptersById = `-- name: GetChaptersById :one
SELECT id, title, body, user_id, status, created_at FROM chapters
WHERE id = $1
`

func (q *Queries) GetChaptersById(ctx context.Context, id int32) (Chapter, error) {
	row := q.db.QueryRow(ctx, getChaptersById, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getChaptersByUser = `-- name: GetChaptersByUser :many
SELECT id, title, body, user_id, status, created_at FROM chapters
WHERE user_id = $1
`

func (q *Queries) GetChaptersByUser(ctx context.Context, userID int32) ([]Chapter, error) {
	rows, err := q.db.Query(ctx, getChaptersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chapter
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVocabularyOfChapter = `-- name: GetVocabularyOfChapter :many
SELECT id, chapter_id, origin_content, description, practice_time, created_at FROM vocabulary
WHERE chapter_id = $1
`

func (q *Queries) GetVocabularyOfChapter(ctx context.Context, chapterID pgtype.Int4) ([]Vocabulary, error) {
	rows, err := q.db.Query(ctx, getVocabularyOfChapter, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vocabulary
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.OriginContent,
			&i.Description,
			&i.PracticeTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
