// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chapter struct {
	ID    int32
	Title pgtype.Text
	// Description for chapter
	Body      pgtype.Text
	UserID    int32
	Status    pgtype.Text
	CreatedAt pgtype.Timestamp
}

type ManageFile struct {
	ID        int32
	Alt       pgtype.Text
	Link      pgtype.Text
	TypeFile  pgtype.Text
	OwnerID   int32
	OwnerType string
	CreatedAt pgtype.Timestamp
}

type RefreshToken struct {
	ID          int32
	UserID      int32
	HashedToken string
	CreatedAt   pgtype.Timestamp
	ExpiresAt   pgtype.Timestamp
}

type User struct {
	ID             int32
	Email          string
	Token          pgtype.Int4
	Role           pgtype.Text
	HashedPassword pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type Vocabulary struct {
	ID            int32
	ChapterID     pgtype.Int4
	OriginContent pgtype.Text
	Description   pgtype.Text
	PracticeTime  pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
}
