// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
)

const getAuthor = `-- name: GetAuthor :one
SELECT id, email, hashed_password, created_at, updated_at, deleted_at FROM users
WHERE email = $1 and deleted_at IS NULL 
LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getAuthor, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, email, hashed_password, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NOT NULL
`

func (q *Queries) ListAuthors(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.HashedPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
