// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vocabulary.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVocabulary = `-- name: CreateVocabulary :one
INSERT INTO vocabulary (chapter_id , origin_content , description)
VALUES ($1, $2, $3)
RETURNING id, chapter_id, origin_content, description, practice_time, created_at
`

type CreateVocabularyParams struct {
	ChapterID     pgtype.Int4
	OriginContent pgtype.Text
	Description   pgtype.Text
}

func (q *Queries) CreateVocabulary(ctx context.Context, arg CreateVocabularyParams) (Vocabulary, error) {
	row := q.db.QueryRow(ctx, createVocabulary, arg.ChapterID, arg.OriginContent, arg.Description)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.OriginContent,
		&i.Description,
		&i.PracticeTime,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVocabularyOfChapter = `-- name: DeleteVocabularyOfChapter :exec
DELETE FROM vocabulary
WHERE chapter_id =  $1
`

func (q *Queries) DeleteVocabularyOfChapter(ctx context.Context, chapterID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteVocabularyOfChapter, chapterID)
	return err
}

const getCharacterVocabulary = `-- name: GetCharacterVocabulary :many
SELECT id, chapter_id, origin_content, description, practice_time, created_at FROM vocabulary
WHERE  chapter_id = $1 
ORDER BY created_at  DESC
LIMIT $2 OFFSET $3
`

type GetCharacterVocabularyParams struct {
	ChapterID pgtype.Int4
	Limit     int32
	Offset    int32
}

func (q *Queries) GetCharacterVocabulary(ctx context.Context, arg GetCharacterVocabularyParams) ([]Vocabulary, error) {
	rows, err := q.db.Query(ctx, getCharacterVocabulary, arg.ChapterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vocabulary
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.OriginContent,
			&i.Description,
			&i.PracticeTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVocabularyOfUser = `-- name: GetVocabularyOfUser :many
SELECT c.id, c.title, c.body, c.user_id, c.status, c.created_at ,  v.id ,  v.origin_content , v.description , v.practice_time , v.created_at FROM chapters as c
INNER JOIN vocabulary as v 
ON c.id = v.chapter_id
WHERE  c.user_id = $1 
ORDER BY v.created_at  DESC
LIMIT $2 OFFSET $3
`

type GetVocabularyOfUserParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

type GetVocabularyOfUserRow struct {
	ID            int32
	Title         pgtype.Text
	Body          pgtype.Text
	UserID        int32
	Status        pgtype.Text
	CreatedAt     pgtype.Timestamp
	ID_2          int32
	OriginContent pgtype.Text
	Description   pgtype.Text
	PracticeTime  pgtype.Timestamp
	CreatedAt_2   pgtype.Timestamp
}

func (q *Queries) GetVocabularyOfUser(ctx context.Context, arg GetVocabularyOfUserParams) ([]GetVocabularyOfUserRow, error) {
	rows, err := q.db.Query(ctx, getVocabularyOfUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVocabularyOfUserRow
	for rows.Next() {
		var i GetVocabularyOfUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.ID_2,
			&i.OriginContent,
			&i.Description,
			&i.PracticeTime,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVocabulary = `-- name: UpdateVocabulary :one
UPDATE vocabulary SET 
origin_content = $2 , description = $3
WHERE id = $1
RETURNING id, chapter_id, origin_content, description, practice_time, created_at
`

type UpdateVocabularyParams struct {
	ID            int32
	OriginContent pgtype.Text
	Description   pgtype.Text
}

func (q *Queries) UpdateVocabulary(ctx context.Context, arg UpdateVocabularyParams) (Vocabulary, error) {
	row := q.db.QueryRow(ctx, updateVocabulary, arg.ID, arg.OriginContent, arg.Description)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.OriginContent,
		&i.Description,
		&i.PracticeTime,
		&i.CreatedAt,
	)
	return i, err
}
